// A set of gerund "thinking" verbs shown beside the spinner while a turn runs.
// One is chosen at random per turn.
const VERBS = [
  "Cogitating",
  "Pondering",
  "Brewing",
  "Conjuring",
  "Forging",
  "Wrangling",
  "Synthesizing",
  "Percolating",
  "Ruminating",
  "Noodling",
  "Computing",
  "Crafting",
  "Composing",
  "Deliberating",
  "Tinkering",
  "Hatching",
  "Incubating",
  "Marinating",
  "Musing",
  "Orchestrating",
  "Puzzling",
  "Scheming",
  "Simmering",
  "Spelunking",
  "Stewing",
  "Summoning",
  "Unfurling",
  "Whirring",
  "Working",
  "Wibbling",
  "Manifesting",
  "Channeling",
  "Concocting",
  "Crunching",
  "Divining",
  "Finagling",
  "Mulling",
  "Plotting",
  "Reticulating",
  "Transmuting",
];

export const randomVerb = (): string => VERBS[Math.floor(Math.random() * VERBS.length)];
